"""
Log Writer Service - Writes deployment logs to logs.md for debugging
Updates every hour with scan statistics and alert information
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import List, Dict

logger = logging.getLogger(__name__)

# Store recent log entries in memory
_recent_logs: List[str] = []
_max_logs = 100  # Keep last 100 log entries


class LogCapture(logging.Handler):
    """Custom handler to capture logs for logs.md"""

    def emit(self, record):
        try:
            log_entry = self.format(record)
            _recent_logs.append(log_entry)

            # Keep only recent logs
            if len(_recent_logs) > _max_logs:
                _recent_logs.pop(0)
        except Exception:
            self.handleError(record)


def install_log_capture():
    """Install log capture handler"""
    try:
        root_logger = logging.getLogger()
        handler = LogCapture()
        handler.setFormatter(logging.Formatter(
            "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
        ))
        handler.setLevel(logging.INFO)
        root_logger.addHandler(handler)
        logger.info("✅ Log capture installed")
    except Exception as e:
        logger.error(f"Failed to install log capture: {e}")


def write_logs_to_file_sync(scan_stats: Dict = None):
    """
    Write current logs to logs.md in repository root (SYNCHRONOUS)

    Args:
        scan_stats: Optional dict with scan statistics
    """
    try:
        logs_file = Path("/app/logs.md")

        # Build markdown content
        content = f"""# Price Alert Bot - Deployment Logs

**Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Current Status

"""

        if scan_stats:
            content += f"""- **Total Scans:** {scan_stats.get('total_scans', 0)}
- **Scan Interval:** {scan_stats.get('scan_interval', 30)}s
- **Running:** {'✅ YES' if scan_stats.get('running', False) else '❌ NO'}
- **Last Scan:** {scan_stats.get('last_scan_time', 'N/A')}

### Recent Scan Results

- **Pairs Checked:** {scan_stats.get('pairs_checked', 0)}
- **Alerts Fired:** {scan_stats.get('alerts_fired', 0)}
- **Errors:** {scan_stats.get('errors', 0)}
- **Duration:** {scan_stats.get('duration', 0):.2f}s

"""

        content += """## Recent Logs (Last 100 entries)

```
"""

        # Add recent logs
        for log_entry in _recent_logs[-100:]:
            content += log_entry + "\n"

        content += """```

## Debug Information

This file is automatically updated every hour by the bot.

If you see:
- ✅ "Session sync complete" - Bot has baseline prices
- ✅ "Fetching ALL Bybit pairs" - Scanner is running
- ✅ "FIRING ALERT" - Alerts are working
- ❌ "No Adjust link found" - AI link finder issue
- ❌ "Alert failed" - Telegram send error

## Key Metrics to Watch

1. **Session Sync**: Should happen once on startup
2. **Scan Count**: Should increase every 30 seconds
3. **Alerts Fired**: Should be > 0 when thresholds are crossed
4. **AI Link Lookups**: Should show "AI found:" messages

---
*Generated by Price Alert Bot v2.0*
"""

        # Write to file
        logs_file.write_text(content)
        logger.info(f"✅ Logs written to {logs_file}")

    except Exception as e:
        logger.error(f"Failed to write logs.md: {e}")


async def write_logs_to_file(scan_stats: Dict = None):
    """
    Async wrapper for write_logs_to_file_sync
    For compatibility with async contexts
    """
    write_logs_to_file_sync(scan_stats)


def get_recent_logs() -> List[str]:
    """Get recent log entries"""
    return _recent_logs.copy()


def clear_logs():
    """Clear stored logs"""
    global _recent_logs
    _recent_logs = []
